### ISSUE TITLE
Error when using Spyder 3.2

### ISSUE THREAD

**Issue by Glader011235** [landlab/landlab#590]
Spyder (versions 3.2.0 and higher) returns an error when trying to run landlab. Everything works fine in Spyder versions 3.1.4 and lower. I'm running the developer version of landlab. 

  File "/Users/RCGlade/landlab/landlab/components/flow_director/flow_direction_DN.py", line 18, in <module>
    from .cfuncs import adjust_flow_receivers

ImportError: cannot import name adjust_flow_receivers

**Comment by kbarnhart** [comment]
@nicgaspar this looks like the same error that you just mentioned in issue #595 

I'm not sure what is causing it, but will think on it.

**Comment by nicgaspar** [comment]
@kbarnhart One more bit of info to add to the mystery... Nathan is running Spyder 3.2.4 and he does not have this issue.

**Comment by Glader011235** [comment]
I also have Python 2.7, so maybe that it is the problem... though I looked at the Spyder docs, and it claims to work with 2.7.

**Comment by nicgaspar** [comment]
I think @margauxmouchene is on to something. I have a computer with Python 2.7 and one with Python 3.5. The failure with Spyder happened on my P 2.7 computer, and then I was afraid to update Spyder on my P 3.5 computer. But Margaux gave me strength... I updated, and no problems!

@Glader011235 Is there a reason to not upgrade your Python?

@mcflugen I was using two different Pythons just to find issues... But should we support 2.7? I realize there are many ways to use Python 2.7 that do not involve Spyder.

**Comment by mcflugen** [comment]
@nicgaspar I think many people are still using Python 2.7 so I don't think we should drop support for it. CSDMS, which is making greater and greater use of landlab, is also tied (unfortunately) to 2.7 - at least for the moment.

**Comment by Glader011235** [comment]
@nicgaspar Interesting, sounds like that's the problem then. I've kept 2.7 because a lot of third party libraries haven't been upgraded to 3 yet... for now I've just reverted to using the older version of Spyder, which works fine.

**Comment by nicgaspar** [comment]
Well at least we solved it maybe, although I guess one bit of evidence doesn't necessarily mean solved. I will keep my 2.7 for now, and just downgrade Spyder. Thanks @Glader011235 @kbarnhart @margauxmouchene @mcflugen We can probably close this unless someone thinks it should remain open.
