### ISSUE TITLE
testing issues on Summit due to nose_tools issue

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#616]
Testing doesn't seem to be able to start after updating landlab to the latest release (post #615 merge) due to a nose_tools related inheritance issue.

Running `python test-installed-landlab.py` yields the following error. 

Summit is a RHEL 7 HPCC platform [specs here](https://rc.colorado.edu/resources/compute/summit)

I was surprised by this since the Travis builds on Linux passed for this branch. 

@mcflugen any ideas?

```
[barnhark@shas0136 scripts]$ python test-installed-landlab.py
landlab version v1.2.0+481.ga4b5873
landlab is installed in /projects/barnhark/landlab/landlab
Python version 2.7.14 |Anaconda, Inc.| (default, Oct 27 2017, 18:21:12) [GCC 7.2.0]
nose version 1.3.7
Traceback (most recent call last):
  File "test-installed-landlab.py", line 35, in <module>
    extra_argv=args, raise_warnings='release')
  File "/projects/barnhark/landlab/landlab/testing/nosetester.py", line 79, in test
    return super(LandlabTester, self).test(**kwds)
  File "/projects/barnhark/conda/lib/python2.7/site-packages/numpy/testing/nose_tools/nosetester.py", line 406, in test
    label, verbose, extra_argv, doctests, coverage, timer)
  File "/projects/barnhark/conda/lib/python2.7/site-packages/numpy/testing/nose_tools/nosetester.py", line 300, in prepare_test_args
    if self.check_fpu_mode:
AttributeError: 'LandlabTester' object has no attribute 'check_fpu_mode'
```

**Comment by mcflugen** [comment]
@kbarnhart I believe the problem is with numpy 1.14. Can you double-check that you have numpy 1.14 installed? If you downgrade to 1.13, the tests should pass. numpy 1.14 also makes some other changes that will make many of our doctests to fail. landlab should be working fine, though.

**Comment by kbarnhart** [comment]
@mcflugen that fixed it! thank you! 

does that mean that we should update requirements.txt to have numpy<1.14?

**Comment by mcflugen** [comment]
@kbarnhart This is maybe something we should discuss with the rest of the group. My opinion is that since landlab still works with numpy 1.14 (even though the tests don't run), I'm not sure we should restrict users to using an older version. Until we fix the incompatibility, we just have to make sure we test with 1.13 or earlier.

**Comment by kbarnhart** [comment]
@mcflugen Based on what you've just written, I agree with your thought to not restrict users numpy versions. Hopefully if someone has this issue before we fix the incompatibility, they'll find this issue and know what is wrong. 

I'll wait until after our next meeting to close the issue in case this comes up and the group decides otherwise.
